// ================================
// ASSET MANAGEMENT DATA MODELS
// ================================

/**
 * Category Interface
 * Represents a category for asset classification
 */
export interface Category {
  /** Unique identifier for the category */
  id: number;

  /** Display name of the category */
  name: string;
}

/**
 * Asset Status Enumeration
 * Defines the possible states an asset can be in
 */
export type AssetStatus = 'Available' | 'Borrowed' | 'Maintenance' | 'Retired';

/**
 * Asset Interface
 * Core data model for asset management system
 */
export interface Asset {
  /** Unique identifier (auto-generated by backend) */
  id?: number;

  /** Asset name - required field */
  name: string;

  /** Asset model/type - required field */
  model: string;

  /** Detailed description - optional field */
  description?: string;

  /** Monetary value in USD - required field */
  value: number;

  /** Foreign key to Category - required field */
  categoryId: number;

  /** Related category object - populated by backend joins */
  category?: Category;

  /** Current status of the asset - optional field with defaults */
  status?: AssetStatus;
}

// ================================
// FORM MODELS (for Reactive Forms)
// ================================

/**
 * Asset Form Data Interface
 * Used for form binding and validation in reactive forms
 */
export interface AssetFormData {
  id: number;
  name: string;
  model: string;
  description: string;
  categoryId: number | null;
  value: number;
}

/**
 * Asset Creation Data Interface
 * Used when creating new assets (excludes auto-generated ID)
 */
export type CreateAssetData = Omit<Asset, 'id'>;

/**
 * Asset Update Data Interface
 * Used for partial updates (all fields optional except ID)
 */
export type UpdateAssetData = Partial<Omit<Asset, 'id'>>;

// ================================
// API RESPONSE MODELS
// ================================

/**
 * API Response Wrapper
 * Standardizes API response format
 */
export interface ApiResponse<T> {
  data: T;
  success: boolean;
  message?: string;
  errors?: string[];
}

/**
 * Paginated Response Interface
 * For future pagination support
 */
export interface PaginatedResponse<T> {
  data: T[];
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  totalPages: number;
}